- Dockerfile
Save assets in a subfolder of the home directory to ensure it gets persisted
#5
> Change assets directory

- Dockerfile
Reverts GeoWerkstatt/geocop#142
> Revert "Change assets directory"

- src/GeoCop.Api/Controllers/ValidationController.cs
Resolves: https://github.com/GeoWerkstatt/geocop/security/code-scanning/3
Resolves: https://github.com/GeoWerkstatt/geocop/security/code-scanning/1
> Sanitize user provided file name

- src/GeoCop.Api/StacServices/StacConverter.cs
Ensures data is properly propagated StacItem internal properties.
Resolves: #141
> Set StacItem DateTime with property setter

- src/GeoCop.Api/Controllers/DeliveryController.cs
- src/GeoCop.Api/Controllers/UserController.cs
- src/GeoCop.Api/Controllers/ValidationController.cs
- src/GeoCop.Api/Controllers/VersionController.cs
> Consolidate SwaggerResponses

- docker-entrypoint.sh
Resolves startup error introduced in #153
> Fixup cp failing on empty directory

- src/GeoCop.Api/Program.cs
> Allow anonymous access to healthcheck

- src/Geopilot.Api/Program.cs
> Set the maximum request body size to 200MB

- .editorconfig
- CHANGELOG.md
- Dockerfile
- config/license.custom.json
- config/license.template.json
- src/Geopilot.Frontend/package-lock.json
- src/Geopilot.Frontend/package.json
Resolves [#156](https://github.com/GeoWerkstatt/geopilot/issues/156)
> Add missing license information

- docker-compose.yml
- src/Geopilot.Api/Controllers/MandateController.cs
- src/Geopilot.Api/Controllers/ValidationController.cs
- src/Geopilot.Api/FileAccess/PhysicalFileProvider.cs
- src/Geopilot.Api/StringExtensions.cs
- tests/.editorconfig
- tests/Geopilot.Api.Test/Controllers/MandateControllerTest.cs
- tests/Geopilot.Api.Test/StringExtensions.cs
Fixes https://github.com/GeoWerkstatt/geopilot/security/code-scanning/15
Fixes https://github.com/GeoWerkstatt/geopilot/security/code-scanning/14
Fixes https://github.com/GeoWerkstatt/geopilot/security/code-scanning/13
Fixes https://github.com/GeoWerkstatt/geopilot/security/code-scanning/12
Supersedes https://github.com/GeoWerkstatt/geopilot/pull/187
> Sanitize user input

- .editorconfig
- .gitattributes
- .github/workflows/release.yml
- CHANGELOG.md
- get-changelog.sh
> Automatically update GitHub release notes

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
> Upgrade GitHub actions

- config/realms/keycloak-geopilot.json
- src/Geopilot.Frontend/src/App.tsx
> Fix: fetch static files crashes application

- CHANGELOG.md
- Geopilot.sln
- src/Geopilot.Api/Authorization/GeopilotUserHandler.cs
- src/Geopilot.Api/ContextExtensions.cs
- src/Geopilot.Api/Controllers/DeliveryController.cs
- src/Geopilot.Api/Controllers/MandateController.cs
- src/Geopilot.Api/Controllers/UserController.cs
- tests/Geopilot.Api.Test/Authorization/GeopilotUserHandlerTest.cs
- tests/Geopilot.Api.Test/ControllerExtensions.cs
- tests/Geopilot.Api.Test/Controllers/DeliveryControllerTest.cs
- tests/Geopilot.Api.Test/Controllers/MandateControllerTest.cs
- tests/Geopilot.Api.Test/Controllers/OrganisationControllerTest.cs
- tests/Geopilot.Api.Test/Controllers/UserControllerTest.cs
- tests/Geopilot.Api.Test/GlobalUsings.cs
- tests/Geopilot.Api.Test/StringExtensionsTest.cs
- tests/Geopilot.Api.Test/TestHelpers.cs
> Register new users in db

- .github/workflows/ci.yml
- CHANGELOG.md
- Directory.Build.props
- Dockerfile
- docker-compose.yml
- docker-entrypoint.sh
- src/Geopilot.Api/ContextExtensions.cs
- src/Geopilot.Api/Controllers/DeliveryController.cs
- src/Geopilot.Api/Controllers/MandateController.cs
- src/Geopilot.Api/Controllers/OrganisationController.cs
- src/Geopilot.Api/Controllers/UserController.cs
- src/Geopilot.Api/Controllers/ValidationController.cs
- src/Geopilot.Api/Controllers/VersionController.cs
- src/Geopilot.Api/Geopilot.Api.csproj
- src/Geopilot.Api/StacServices/HttpsLinkGenerator.cs
- src/Geopilot.Api/StacServices/StacConverter.cs
- src/Geopilot.Api/StacServices/StacItemsProvider.cs
- src/Geopilot.Api/StacServices/StacLinker.cs
- src/Geopilot.Api/StringExtensions.cs
- src/Geopilot.Api/Validation/Interlis/InterlisValidator.cs
- src/Geopilot.Api/Validation/ValidationFailedException.cs
- tests/Geopilot.Api.Test/Controllers/DeliveryControllerTest.cs
- tests/Geopilot.Api.Test/Controllers/VersionControllerTest.cs
- tests/Geopilot.Api.Test/Geopilot.Api.Test.csproj
- tests/Geopilot.Api.Test/StacServices/StacConverterTest.cs
Changes the port of the docker image to 8080 and runs as `app` user.
Resolves #249
> Update to .NET 8

- src/Geopilot.Api/StacServices/HttpsStacApiContextFactory.cs
- src/Geopilot.Api/StacServices/StacItemsProvider.cs
- tests/.editorconfig
- tests/Geopilot.Api.Test/Geopilot.Api.Test.csproj
- tests/Geopilot.Api.Test/GeopilotApiApp.cs
- tests/Geopilot.Api.Test/Program.cs
- tests/Geopilot.Api.Test/StacApi/CatalogTest.cs
- tests/Geopilot.Api.Test/StacApi/CollectionsTest.cs
- tests/Geopilot.Api.Test/StacApi/FeaturesTest.cs
- tests/Geopilot.Api.Test/StacApi/SearchTest.cs
> Return relevant items in STAC search

- .github/workflows/release.yml
> Add major version Docker image tag

- .github/workflows/cypress.yml
- .gitignore
- README.md
- docker-compose.yml
- src/Geopilot.Frontend/cypress.config.js
- src/Geopilot.Frontend/vite.config.js
> Add HTTPS support for Dev & Cypress

- src/Geopilot.Frontend/public/locale/de/common.json
- src/Geopilot.Frontend/public/locale/en/common.json
- src/Geopilot.Frontend/public/locale/fr/common.json
- src/Geopilot.Frontend/public/locale/it/common.json
- src/Geopilot.Frontend/src/components/fileDropzone.tsx
> Fix translation

- src/Geopilot.Frontend/src/appTheme.ts
- src/Geopilot.Frontend/src/components/header/header.tsx
- src/Geopilot.Frontend/src/mui.theme.d.ts
> Fix line break

- .github/workflows/ci.yml
Checks if migrations ans Models are in sync.
> Enable EF migration check

- src/Geopilot.Api/ContextExtensions.cs
- src/Geopilot.Api/Models/Mandate.cs
> Limit EvaluatePartial to NotEvaluated and Required

- src/Geopilot.Frontend/cypress/e2e/delivery.cy.js
- src/Geopilot.Frontend/cypress/e2e/deliveryOverview.cy.js
- src/Geopilot.Frontend/cypress/e2e/helpers/deliveryHelpers.js
- src/Geopilot.Frontend/cypress/fixtures/deliveryFiles/ilimodels_valid.xml
- src/Geopilot.Frontend/src/pages/admin/deliveryOverview.tsx
> Delivery overview tests

- src/Geopilot.Frontend/public/locale/it/common.json
> Fix translation key

- Geopilot.slnLaunch
- README.md
Remove remarks needed without launch profile feature
> Add VS 2022 launch profile

- src/Geopilot.Frontend/src/components/adminDetailForm.tsx
- src/Geopilot.Frontend/src/pages/admin/userDetail.tsx
> Fix double edit on user edit

- CHANGELOG.md
- src/Geopilot.Api/Program.cs
- src/Geopilot.Frontend/cypress/e2e/delivery.cy.js
- src/Geopilot.Frontend/cypress/e2e/helpers/appHelpers.js
- src/Geopilot.Frontend/public/locale/de/common.json
- src/Geopilot.Frontend/public/locale/en/common.json
- src/Geopilot.Frontend/public/locale/fr/common.json
- src/Geopilot.Frontend/public/locale/it/common.json
- src/Geopilot.Frontend/src/components/fileDropzone.tsx
RESOLVES: #376 
- Adjusted variables in frontend & api to not accept files over 100MB
> #376 Limit file uploads to 100MB

- CHANGELOG.md
- src/Geopilot.Frontend/src/pages/admin/mandates.tsx
- src/Geopilot.Frontend/src/pages/admin/organisations.tsx
- src/Geopilot.Frontend/src/pages/admin/users.tsx
RESOLVES: #385 
- Fixed Sorting in admin tables by converting all aggregated values to simple strings
- Filtering functionality enabled automatically after performing previous step
> 385 Sorting and Filtering in Admin Tables

- CHANGELOG.md
- src/Geopilot.Api/Validation/Interlis/InterlisSettingsResponse.cs
- src/Geopilot.Api/Validation/Interlis/InterlisStatusResponse.cs
- src/Geopilot.Api/Validation/Interlis/InterlisUploadResponse.cs
- src/Geopilot.Api/Validation/Interlis/InterlisValidator.cs
- src/Geopilot.Frontend/cypress/e2e/delivery.cy.js
- Renamed a bunch of files and variables, that's it.
> Purged ilicheck from geopilots realm
